# Generated by Django 4.0.5 on 2022-07-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_user_listing_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='user',
        ),
    ]
