# Generated by Django 4.0.5 on 2022-07-12 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlisted',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
